debian: add acrn-hypervisor.prerm.in
Signed-off-by: Helmut Buchsbaum <helmut.buchsbaum@opensource.tttech-industrial.com>

diff --git a/debian/acrn-hypervisor.prerm.in b/debian/acrn-hypervisor.prerm.in
--- a/debian/acrn-hypervisor.prerm.in
+++ b/debian/acrn-hypervisor.prerm.in
@@ -1,26 +1,24 @@
 #!/bin/sh
-# postrm script for acrn-hypervisor
+# prerm script for acrn-hypervisor
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <overwriter>
-#          <overwriter-version>
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    remove)
+    remove|upgrade|deconfigure)
         rm -f /boot/acrn-@acrnversion@.out
         rm -f /boot/acrn-@acrnversion@.config
         rm -f /boot/acrn-@acrnversion@.map
@@ -29,11 +27,12 @@ case "$1" in
             update-grub || :
         fi
     ;;
-    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+
+    failed-upgrade)
     ;;
 
     *)
-        echo "postrm called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
